name: Lint
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
        architecture: x64
    - run: pip install .[dev]
    - run: black --check *.py */
    - run: isort --check-only *.py */
    - run: flake8
